#!/bin/sh

set -x

APP=/Applications/R-VPN.app
AGENT=/usr/local/bin/rvpn
LOG_FILE=/var/log/rvpn/install.log

mkdir -p /var/log/rvpn/
mkdir -p /usr/local/bin/

{
    echo "Installing R-VPN..."

    if test -d $APP; then
        echo "R-VPN app copied successfully."
    else
        echo "R-VPN app could not be copied to the Applications folder."
        exit 1
    fi

    ln -fs $APP/Contents/MacOS/R-VPN $AGENT
    if test -f $AGENT; then
        echo "R-VPN binary linked successfully."
    else
        echo "R-VPN could not create symlink to /usr/local/bin"
        exit 1
    fi

    $AGENT service install || true
    $AGENT service start > /dev/null 2>&1 &

    open $APP

    echo "Finished R-VPN installation successfully"
    exit 0 # all good
} &> $LOG_FILE
